#!/usr/bin/env python3
# pylint: disable=invalid-name
"""Generate a zephyr board from a litex export"""

import os
import sys

from litex_zephyr_export.svd_parser import SvdParser

SVD_PATH = "csr.svd"


def main():
    """Script entry point"""
    parser = SvdParser()

    try:
        parser.parse_file(SVD_PATH)

    except FileNotFoundError as ex:
        print(f"Could not open SVD export {SVD_PATH}: {ex}", file=sys.stderr)
        sys.exit(os.EX_NOINPUT)

    except RuntimeError as ex:
        print(f"Error while parsing {SVD_PATH}: {ex}", file=sys.stderr)
        sys.exit(os.EX_DATAERR)


if __name__ == "__main__":
    main()
