#!/usr/bin/env python3
# pylint: disable=invalid-name
"""Generate a zephyr board from a litex export"""


def main():
    """Script entry point"""
    print("Hello World!")


if __name__ == "__main__":
    main()
